default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: developmentdb
  username: lisa

test:
  <<: *default
  encoding: unicode
  database: testdatabase
  username: lisa

production:
  <<: *default